//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace SFUpdateJobDesc.com.successfactors.sfapi {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The operation binding 'getJobResult' from namespace 'urn:server.sfapi.successfactors.com' was ignored.  Missing soap:body output binding.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SFAPISoapBinding", Namespace="urn:server.sfapi.successfactors.com")]
    public partial class SFAPIService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback loginOperationCompleted;
        
        private System.Threading.SendOrPostCallback isValidSessionOperationCompleted;
        
        private System.Threading.SendOrPostCallback describeOperationCompleted;
        
        private System.Threading.SendOrPostCallback describeExOperationCompleted;
        
        private System.Threading.SendOrPostCallback logoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback listOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryMoreOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateOperationCompleted;
        
        private System.Threading.SendOrPostCallback upsertOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback submitQueryJobOperationCompleted;
        
        private System.Threading.SendOrPostCallback getJobResultEmbeddedOperationCompleted;
        
        private System.Threading.SendOrPostCallback getJobStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback listJobsOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelJobOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SFAPIService() {
            this.Url = global::SFUpdateJobDesc.Properties.Settings.Default.SFUpdateJobDesc_com_successfactors_sfapi_SFAPIService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;
        
        /// <remarks/>
        public event isValidSessionCompletedEventHandler isValidSessionCompleted;
        
        /// <remarks/>
        public event describeCompletedEventHandler describeCompleted;
        
        /// <remarks/>
        public event describeExCompletedEventHandler describeExCompleted;
        
        /// <remarks/>
        public event logoutCompletedEventHandler logoutCompleted;
        
        /// <remarks/>
        public event listCompletedEventHandler listCompleted;
        
        /// <remarks/>
        public event queryCompletedEventHandler queryCompleted;
        
        /// <remarks/>
        public event queryMoreCompletedEventHandler queryMoreCompleted;
        
        /// <remarks/>
        public event insertCompletedEventHandler insertCompleted;
        
        /// <remarks/>
        public event updateCompletedEventHandler updateCompleted;
        
        /// <remarks/>
        public event upsertCompletedEventHandler upsertCompleted;
        
        /// <remarks/>
        public event deleteCompletedEventHandler deleteCompleted;
        
        /// <remarks/>
        public event submitQueryJobCompletedEventHandler submitQueryJobCompleted;
        
        /// <remarks/>
        public event getJobResultEmbeddedCompletedEventHandler getJobResultEmbeddedCompleted;
        
        /// <remarks/>
        public event getJobStatusCompletedEventHandler getJobStatusCompleted;
        
        /// <remarks/>
        public event listJobsCompletedEventHandler listJobsCompleted;
        
        /// <remarks/>
        public event cancelJobCompletedEventHandler cancelJobCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:sfobject.sfapi.successfactors.com", ResponseNamespace="urn:sfobject.sfapi.successfactors.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public LoginResult login(SFCredential credential, [System.Xml.Serialization.XmlElementAttribute("param")] SFParameter[] param) {
            object[] results = this.Invoke("login", new object[] {
                        credential,
                        param});
            return ((LoginResult)(results[0]));
        }
        
        /// <remarks/>
        public void loginAsync(SFCredential credential, SFParameter[] param) {
            this.loginAsync(credential, param, null);
        }
        
        /// <remarks/>
        public void loginAsync(SFCredential credential, SFParameter[] param, object userState) {
            if ((this.loginOperationCompleted == null)) {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                        credential,
                        param}, this.loginOperationCompleted, userState);
        }
        
        private void OnloginOperationCompleted(object arg) {
            if ((this.loginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:sfobject.sfapi.successfactors.com", ResponseNamespace="urn:sfobject.sfapi.successfactors.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public bool isValidSession() {
            object[] results = this.Invoke("isValidSession", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void isValidSessionAsync() {
            this.isValidSessionAsync(null);
        }
        
        /// <remarks/>
        public void isValidSessionAsync(object userState) {
            if ((this.isValidSessionOperationCompleted == null)) {
                this.isValidSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisValidSessionOperationCompleted);
            }
            this.InvokeAsync("isValidSession", new object[0], this.isValidSessionOperationCompleted, userState);
        }
        
        private void OnisValidSessionOperationCompleted(object arg) {
            if ((this.isValidSessionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isValidSessionCompleted(this, new isValidSessionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestElementName="describeSFObjects", RequestNamespace="urn:sfobject.sfapi.successfactors.com", ResponseElementName="describeSFObjectsResponse", ResponseNamespace="urn:sfobject.sfapi.successfactors.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public DescribeResult[] describe([System.Xml.Serialization.XmlElementAttribute("type")] string[] type, [System.Xml.Serialization.XmlElementAttribute("param")] SFParameter[] param) {
            object[] results = this.Invoke("describe", new object[] {
                        type,
                        param});
            return ((DescribeResult[])(results[0]));
        }
        
        /// <remarks/>
        public void describeAsync(string[] type, SFParameter[] param) {
            this.describeAsync(type, param, null);
        }
        
        /// <remarks/>
        public void describeAsync(string[] type, SFParameter[] param, object userState) {
            if ((this.describeOperationCompleted == null)) {
                this.describeOperationCompleted = new System.Threading.SendOrPostCallback(this.OndescribeOperationCompleted);
            }
            this.InvokeAsync("describe", new object[] {
                        type,
                        param}, this.describeOperationCompleted, userState);
        }
        
        private void OndescribeOperationCompleted(object arg) {
            if ((this.describeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.describeCompleted(this, new describeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestElementName="describeSFObjectsEx", RequestNamespace="urn:sfobject.sfapi.successfactors.com", ResponseElementName="describeSFObjectsExResponse", ResponseNamespace="urn:sfobject.sfapi.successfactors.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public DescribeExResult[] describeEx([System.Xml.Serialization.XmlElementAttribute("type")] string[] type, [System.Xml.Serialization.XmlElementAttribute("param")] SFParameter[] param) {
            object[] results = this.Invoke("describeEx", new object[] {
                        type,
                        param});
            return ((DescribeExResult[])(results[0]));
        }
        
        /// <remarks/>
        public void describeExAsync(string[] type, SFParameter[] param) {
            this.describeExAsync(type, param, null);
        }
        
        /// <remarks/>
        public void describeExAsync(string[] type, SFParameter[] param, object userState) {
            if ((this.describeExOperationCompleted == null)) {
                this.describeExOperationCompleted = new System.Threading.SendOrPostCallback(this.OndescribeExOperationCompleted);
            }
            this.InvokeAsync("describeEx", new object[] {
                        type,
                        param}, this.describeExOperationCompleted, userState);
        }
        
        private void OndescribeExOperationCompleted(object arg) {
            if ((this.describeExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.describeExCompleted(this, new describeExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:sfobject.sfapi.successfactors.com", ResponseNamespace="urn:sfobject.sfapi.successfactors.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public bool logout() {
            object[] results = this.Invoke("logout", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void logoutAsync() {
            this.logoutAsync(null);
        }
        
        /// <remarks/>
        public void logoutAsync(object userState) {
            if ((this.logoutOperationCompleted == null)) {
                this.logoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlogoutOperationCompleted);
            }
            this.InvokeAsync("logout", new object[0], this.logoutOperationCompleted, userState);
        }
        
        private void OnlogoutOperationCompleted(object arg) {
            if ((this.logoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.logoutCompleted(this, new logoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestElementName="listSFObjects", RequestNamespace="urn:sfobject.sfapi.successfactors.com", ResponseElementName="listSFObjectsResponse", ResponseNamespace="urn:sfobject.sfapi.successfactors.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("name")]
        public string[] list() {
            object[] results = this.Invoke("list", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void listAsync() {
            this.listAsync(null);
        }
        
        /// <remarks/>
        public void listAsync(object userState) {
            if ((this.listOperationCompleted == null)) {
                this.listOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistOperationCompleted);
            }
            this.InvokeAsync("list", new object[0], this.listOperationCompleted, userState);
        }
        
        private void OnlistOperationCompleted(object arg) {
            if ((this.listCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listCompleted(this, new listCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:sfobject.sfapi.successfactors.com", ResponseNamespace="urn:sfobject.sfapi.successfactors.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public QueryResult query(string queryString, [System.Xml.Serialization.XmlElementAttribute("param")] SFParameter[] param) {
            object[] results = this.Invoke("query", new object[] {
                        queryString,
                        param});
            return ((QueryResult)(results[0]));
        }
        
        /// <remarks/>
        public void queryAsync(string queryString, SFParameter[] param) {
            this.queryAsync(queryString, param, null);
        }
        
        /// <remarks/>
        public void queryAsync(string queryString, SFParameter[] param, object userState) {
            if ((this.queryOperationCompleted == null)) {
                this.queryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryOperationCompleted);
            }
            this.InvokeAsync("query", new object[] {
                        queryString,
                        param}, this.queryOperationCompleted, userState);
        }
        
        private void OnqueryOperationCompleted(object arg) {
            if ((this.queryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryCompleted(this, new queryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:sfobject.sfapi.successfactors.com", ResponseNamespace="urn:sfobject.sfapi.successfactors.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public QueryResult queryMore(string querySessionId) {
            object[] results = this.Invoke("queryMore", new object[] {
                        querySessionId});
            return ((QueryResult)(results[0]));
        }
        
        /// <remarks/>
        public void queryMoreAsync(string querySessionId) {
            this.queryMoreAsync(querySessionId, null);
        }
        
        /// <remarks/>
        public void queryMoreAsync(string querySessionId, object userState) {
            if ((this.queryMoreOperationCompleted == null)) {
                this.queryMoreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryMoreOperationCompleted);
            }
            this.InvokeAsync("queryMore", new object[] {
                        querySessionId}, this.queryMoreOperationCompleted, userState);
        }
        
        private void OnqueryMoreOperationCompleted(object arg) {
            if ((this.queryMoreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryMoreCompleted(this, new queryMoreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:sfobject.sfapi.successfactors.com", ResponseNamespace="urn:sfobject.sfapi.successfactors.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public InsertResult insert(string type, [System.Xml.Serialization.XmlElementAttribute("sfobject")] SFObject[] sfobject, [System.Xml.Serialization.XmlElementAttribute("processingParam")] SFParameter[] processingParam) {
            object[] results = this.Invoke("insert", new object[] {
                        type,
                        sfobject,
                        processingParam});
            return ((InsertResult)(results[0]));
        }
        
        /// <remarks/>
        public void insertAsync(string type, SFObject[] sfobject, SFParameter[] processingParam) {
            this.insertAsync(type, sfobject, processingParam, null);
        }
        
        /// <remarks/>
        public void insertAsync(string type, SFObject[] sfobject, SFParameter[] processingParam, object userState) {
            if ((this.insertOperationCompleted == null)) {
                this.insertOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertOperationCompleted);
            }
            this.InvokeAsync("insert", new object[] {
                        type,
                        sfobject,
                        processingParam}, this.insertOperationCompleted, userState);
        }
        
        private void OninsertOperationCompleted(object arg) {
            if ((this.insertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertCompleted(this, new insertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:sfobject.sfapi.successfactors.com", ResponseNamespace="urn:sfobject.sfapi.successfactors.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public UpdateResult update(string type, [System.Xml.Serialization.XmlElementAttribute("sfobject")] SFObject[] sfobject, [System.Xml.Serialization.XmlElementAttribute("processingParam")] SFParameter[] processingParam) {
            object[] results = this.Invoke("update", new object[] {
                        type,
                        sfobject,
                        processingParam});
            return ((UpdateResult)(results[0]));
        }
        
        /// <remarks/>
        public void updateAsync(string type, SFObject[] sfobject, SFParameter[] processingParam) {
            this.updateAsync(type, sfobject, processingParam, null);
        }
        
        /// <remarks/>
        public void updateAsync(string type, SFObject[] sfobject, SFParameter[] processingParam, object userState) {
            if ((this.updateOperationCompleted == null)) {
                this.updateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateOperationCompleted);
            }
            this.InvokeAsync("update", new object[] {
                        type,
                        sfobject,
                        processingParam}, this.updateOperationCompleted, userState);
        }
        
        private void OnupdateOperationCompleted(object arg) {
            if ((this.updateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateCompleted(this, new updateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:sfobject.sfapi.successfactors.com", ResponseNamespace="urn:sfobject.sfapi.successfactors.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public UpsertResult upsert(string type, [System.Xml.Serialization.XmlElementAttribute("sfobject")] SFObject[] sfobject, [System.Xml.Serialization.XmlElementAttribute("processingParam")] SFParameter[] processingParam) {
            object[] results = this.Invoke("upsert", new object[] {
                        type,
                        sfobject,
                        processingParam});
            return ((UpsertResult)(results[0]));
        }
        
        /// <remarks/>
        public void upsertAsync(string type, SFObject[] sfobject, SFParameter[] processingParam) {
            this.upsertAsync(type, sfobject, processingParam, null);
        }
        
        /// <remarks/>
        public void upsertAsync(string type, SFObject[] sfobject, SFParameter[] processingParam, object userState) {
            if ((this.upsertOperationCompleted == null)) {
                this.upsertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupsertOperationCompleted);
            }
            this.InvokeAsync("upsert", new object[] {
                        type,
                        sfobject,
                        processingParam}, this.upsertOperationCompleted, userState);
        }
        
        private void OnupsertOperationCompleted(object arg) {
            if ((this.upsertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.upsertCompleted(this, new upsertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:sfobject.sfapi.successfactors.com", ResponseNamespace="urn:sfobject.sfapi.successfactors.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public DeleteResult delete(string type, [System.Xml.Serialization.XmlElementAttribute("sfobject")] SFObject[] sfobject, [System.Xml.Serialization.XmlElementAttribute("processingParam")] SFParameter[] processingParam) {
            object[] results = this.Invoke("delete", new object[] {
                        type,
                        sfobject,
                        processingParam});
            return ((DeleteResult)(results[0]));
        }
        
        /// <remarks/>
        public void deleteAsync(string type, SFObject[] sfobject, SFParameter[] processingParam) {
            this.deleteAsync(type, sfobject, processingParam, null);
        }
        
        /// <remarks/>
        public void deleteAsync(string type, SFObject[] sfobject, SFParameter[] processingParam, object userState) {
            if ((this.deleteOperationCompleted == null)) {
                this.deleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteOperationCompleted);
            }
            this.InvokeAsync("delete", new object[] {
                        type,
                        sfobject,
                        processingParam}, this.deleteOperationCompleted, userState);
        }
        
        private void OndeleteOperationCompleted(object arg) {
            if ((this.deleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteCompleted(this, new deleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("submitQueryJobResponse", Namespace="urn:sfobject.sfapi.successfactors.com")]
        public submitQueryJobResponse submitQueryJob([System.Xml.Serialization.XmlElementAttribute("submitQueryJob", Namespace="urn:sfobject.sfapi.successfactors.com")] submitQueryJob submitQueryJob1) {
            object[] results = this.Invoke("submitQueryJob", new object[] {
                        submitQueryJob1});
            return ((submitQueryJobResponse)(results[0]));
        }
        
        /// <remarks/>
        public void submitQueryJobAsync(submitQueryJob submitQueryJob1) {
            this.submitQueryJobAsync(submitQueryJob1, null);
        }
        
        /// <remarks/>
        public void submitQueryJobAsync(submitQueryJob submitQueryJob1, object userState) {
            if ((this.submitQueryJobOperationCompleted == null)) {
                this.submitQueryJobOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsubmitQueryJobOperationCompleted);
            }
            this.InvokeAsync("submitQueryJob", new object[] {
                        submitQueryJob1}, this.submitQueryJobOperationCompleted, userState);
        }
        
        private void OnsubmitQueryJobOperationCompleted(object arg) {
            if ((this.submitQueryJobCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.submitQueryJobCompleted(this, new submitQueryJobCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getJobResultEmbeddedResponse", Namespace="urn:sfobject.sfapi.successfactors.com", DataType="base64Binary")]
        public byte[] getJobResultEmbedded([System.Xml.Serialization.XmlElementAttribute("getJobResultEmbedded", Namespace="urn:sfobject.sfapi.successfactors.com")] getJobResultEmbedded getJobResultEmbedded1) {
            object[] results = this.Invoke("getJobResultEmbedded", new object[] {
                        getJobResultEmbedded1});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void getJobResultEmbeddedAsync(getJobResultEmbedded getJobResultEmbedded1) {
            this.getJobResultEmbeddedAsync(getJobResultEmbedded1, null);
        }
        
        /// <remarks/>
        public void getJobResultEmbeddedAsync(getJobResultEmbedded getJobResultEmbedded1, object userState) {
            if ((this.getJobResultEmbeddedOperationCompleted == null)) {
                this.getJobResultEmbeddedOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetJobResultEmbeddedOperationCompleted);
            }
            this.InvokeAsync("getJobResultEmbedded", new object[] {
                        getJobResultEmbedded1}, this.getJobResultEmbeddedOperationCompleted, userState);
        }
        
        private void OngetJobResultEmbeddedOperationCompleted(object arg) {
            if ((this.getJobResultEmbeddedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getJobResultEmbeddedCompleted(this, new getJobResultEmbeddedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:sfobject.sfapi.successfactors.com", ResponseNamespace="urn:sfobject.sfapi.successfactors.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public TaskStatus getJobStatus(string taskId) {
            object[] results = this.Invoke("getJobStatus", new object[] {
                        taskId});
            return ((TaskStatus)(results[0]));
        }
        
        /// <remarks/>
        public void getJobStatusAsync(string taskId) {
            this.getJobStatusAsync(taskId, null);
        }
        
        /// <remarks/>
        public void getJobStatusAsync(string taskId, object userState) {
            if ((this.getJobStatusOperationCompleted == null)) {
                this.getJobStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetJobStatusOperationCompleted);
            }
            this.InvokeAsync("getJobStatus", new object[] {
                        taskId}, this.getJobStatusOperationCompleted, userState);
        }
        
        private void OngetJobStatusOperationCompleted(object arg) {
            if ((this.getJobStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getJobStatusCompleted(this, new getJobStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:sfobject.sfapi.successfactors.com", ResponseNamespace="urn:sfobject.sfapi.successfactors.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public TaskStatus[] listJobs() {
            object[] results = this.Invoke("listJobs", new object[0]);
            return ((TaskStatus[])(results[0]));
        }
        
        /// <remarks/>
        public void listJobsAsync() {
            this.listJobsAsync(null);
        }
        
        /// <remarks/>
        public void listJobsAsync(object userState) {
            if ((this.listJobsOperationCompleted == null)) {
                this.listJobsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistJobsOperationCompleted);
            }
            this.InvokeAsync("listJobs", new object[0], this.listJobsOperationCompleted, userState);
        }
        
        private void OnlistJobsOperationCompleted(object arg) {
            if ((this.listJobsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listJobsCompleted(this, new listJobsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:sfobject.sfapi.successfactors.com", ResponseNamespace="urn:sfobject.sfapi.successfactors.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public TaskStatus cancelJob(string taskId) {
            object[] results = this.Invoke("cancelJob", new object[] {
                        taskId});
            return ((TaskStatus)(results[0]));
        }
        
        /// <remarks/>
        public void cancelJobAsync(string taskId) {
            this.cancelJobAsync(taskId, null);
        }
        
        /// <remarks/>
        public void cancelJobAsync(string taskId, object userState) {
            if ((this.cancelJobOperationCompleted == null)) {
                this.cancelJobOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelJobOperationCompleted);
            }
            this.InvokeAsync("cancelJob", new object[] {
                        taskId}, this.cancelJobOperationCompleted, userState);
        }
        
        private void OncancelJobOperationCompleted(object arg) {
            if ((this.cancelJobCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelJobCompleted(this, new cancelJobCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfobject.sfapi.successfactors.com")]
    public partial class SFCredential {
        
        private string companyIdField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string developerKeyField;
        
        /// <remarks/>
        public string companyId {
            get {
                return this.companyIdField;
            }
            set {
                this.companyIdField = value;
            }
        }
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string developerKey {
            get {
                return this.developerKeyField;
            }
            set {
                this.developerKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfobject.sfapi.successfactors.com")]
    public partial class TaskResultStatus {
        
        private string taskResultIdField;
        
        private string lastFinishTimeField;
        
        private string lastStartTimeField;
        
        private string validUntilField;
        
        private string errorCodeField;
        
        private string messageField;
        
        private TaskResultStatusEnum statusField;
        
        /// <remarks/>
        public string taskResultId {
            get {
                return this.taskResultIdField;
            }
            set {
                this.taskResultIdField = value;
            }
        }
        
        /// <remarks/>
        public string lastFinishTime {
            get {
                return this.lastFinishTimeField;
            }
            set {
                this.lastFinishTimeField = value;
            }
        }
        
        /// <remarks/>
        public string lastStartTime {
            get {
                return this.lastStartTimeField;
            }
            set {
                this.lastStartTimeField = value;
            }
        }
        
        /// <remarks/>
        public string validUntil {
            get {
                return this.validUntilField;
            }
            set {
                this.validUntilField = value;
            }
        }
        
        /// <remarks/>
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public TaskResultStatusEnum status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfobject.sfapi.successfactors.com")]
    public enum TaskResultStatusEnum {
        
        /// <remarks/>
        running,
        
        /// <remarks/>
        finished,
        
        /// <remarks/>
        failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfobject.sfapi.successfactors.com")]
    public partial class TaskStatus {
        
        private string taskIdField;
        
        private string taskNameField;
        
        private string createDateField;
        
        private TaskStatusEnum statusField;
        
        private TaskResultStatus taskResultField;
        
        /// <remarks/>
        public string taskId {
            get {
                return this.taskIdField;
            }
            set {
                this.taskIdField = value;
            }
        }
        
        /// <remarks/>
        public string taskName {
            get {
                return this.taskNameField;
            }
            set {
                this.taskNameField = value;
            }
        }
        
        /// <remarks/>
        public string createDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        public TaskStatusEnum status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public TaskResultStatus taskResult {
            get {
                return this.taskResultField;
            }
            set {
                this.taskResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfobject.sfapi.successfactors.com")]
    public enum TaskStatusEnum {
        
        /// <remarks/>
        unsubmitted,
        
        /// <remarks/>
        submitted,
        
        /// <remarks/>
        processing,
        
        /// <remarks/>
        finished,
        
        /// <remarks/>
        failed,
        
        /// <remarks/>
        undefined,
        
        /// <remarks/>
        cancelled,
        
        /// <remarks/>
        deleted,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfobject.sfapi.successfactors.com")]
    public partial class DeleteResult {
        
        private string jobStatusField;
        
        private string messageField;
        
        private ObjectEditResult[] objectEditResultField;
        
        /// <remarks/>
        public string jobStatus {
            get {
                return this.jobStatusField;
            }
            set {
                this.jobStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objectEditResult", IsNullable=true)]
        public ObjectEditResult[] objectEditResult {
            get {
                return this.objectEditResultField;
            }
            set {
                this.objectEditResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfobject.sfapi.successfactors.com")]
    public partial class ObjectEditResult {
        
        private string idField;
        
        private string errorStatusField;
        
        private string editStatusField;
        
        private System.Nullable<int> indexField;
        
        private string messageField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string errorStatus {
            get {
                return this.errorStatusField;
            }
            set {
                this.errorStatusField = value;
            }
        }
        
        /// <remarks/>
        public string editStatus {
            get {
                return this.editStatusField;
            }
            set {
                this.editStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfobject.sfapi.successfactors.com")]
    public partial class UpsertResult {
        
        private string jobStatusField;
        
        private string messageField;
        
        private ObjectEditResult[] objectEditResultField;
        
        /// <remarks/>
        public string jobStatus {
            get {
                return this.jobStatusField;
            }
            set {
                this.jobStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objectEditResult", IsNullable=true)]
        public ObjectEditResult[] objectEditResult {
            get {
                return this.objectEditResultField;
            }
            set {
                this.objectEditResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfobject.sfapi.successfactors.com")]
    public partial class UpdateResult {
        
        private string jobStatusField;
        
        private string messageField;
        
        private ObjectEditResult[] objectEditResultField;
        
        /// <remarks/>
        public string jobStatus {
            get {
                return this.jobStatusField;
            }
            set {
                this.jobStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objectEditResult", IsNullable=true)]
        public ObjectEditResult[] objectEditResult {
            get {
                return this.objectEditResultField;
            }
            set {
                this.objectEditResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfobject.sfapi.successfactors.com")]
    public partial class InsertResult {
        
        private string jobStatusField;
        
        private string messageField;
        
        private ObjectEditResult[] objectEditResultField;
        
        /// <remarks/>
        public string jobStatus {
            get {
                return this.jobStatusField;
            }
            set {
                this.jobStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objectEditResult", IsNullable=true)]
        public ObjectEditResult[] objectEditResult {
            get {
                return this.objectEditResultField;
            }
            set {
                this.objectEditResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfobject.sfapi.successfactors.com")]
    public partial class BusinessKeys {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfobject.sfapi.successfactors.com")]
    public partial class SFObject {
        
        private object itemField;
        
        private string typeField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("businessKeys", typeof(BusinessKeys))]
        [System.Xml.Serialization.XmlElementAttribute("id", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfobject.sfapi.successfactors.com")]
    public partial class QueryResult {
        
        private SFObject[] sfobjectField;
        
        private int numResultsField;
        
        private bool hasMoreField;
        
        private string querySessionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sfobject")]
        public SFObject[] sfobject {
            get {
                return this.sfobjectField;
            }
            set {
                this.sfobjectField = value;
            }
        }
        
        /// <remarks/>
        public int numResults {
            get {
                return this.numResultsField;
            }
            set {
                this.numResultsField = value;
            }
        }
        
        /// <remarks/>
        public bool hasMore {
            get {
                return this.hasMoreField;
            }
            set {
                this.hasMoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string querySessionId {
            get {
                return this.querySessionIdField;
            }
            set {
                this.querySessionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfobject.sfapi.successfactors.com")]
    public partial class FieldEx {
        
        private string nameField;
        
        private dataType dataTypeField;
        
        private Picklist picklistField;
        
        private Label[] labelField;
        
        private int maxlengthField;
        
        private bool maxlengthFieldSpecified;
        
        private bool requiredField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public dataType dataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        public Picklist picklist {
            get {
                return this.picklistField;
            }
            set {
                this.picklistField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("label")]
        public Label[] label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        public int maxlength {
            get {
                return this.maxlengthField;
            }
            set {
                this.maxlengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxlengthSpecified {
            get {
                return this.maxlengthFieldSpecified;
            }
            set {
                this.maxlengthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool required {
            get {
                return this.requiredField;
            }
            set {
                this.requiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfobject.sfapi.successfactors.com")]
    public enum dataType {
        
        /// <remarks/>
        @string,
        
        /// <remarks/>
        date,
        
        /// <remarks/>
        datetime,
        
        /// <remarks/>
        @int,
        
        /// <remarks/>
        @long,
        
        /// <remarks/>
        @float,
        
        /// <remarks/>
        @double,
        
        /// <remarks/>
        boolean,
        
        /// <remarks/>
        binary,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfobject.sfapi.successfactors.com")]
    public partial class Picklist {
        
        private string idField;
        
        private string sourceField;
        
        private PicklistOption[] picklistOptionField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("picklistOption")]
        public PicklistOption[] picklistOption {
            get {
                return this.picklistOptionField;
            }
            set {
                this.picklistOptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfobject.sfapi.successfactors.com")]
    public partial class PicklistOption {
        
        private long idField;
        
        private Label[] labelField;
        
        private string statusField;
        
        private double valueField;
        
        private string externalCodeField;
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("label")]
        public Label[] label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public double value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string externalCode {
            get {
                return this.externalCodeField;
            }
            set {
                this.externalCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfobject.sfapi.successfactors.com")]
    public partial class Label {
        
        private string valueField;
        
        private string localeField;
        
        private string mimetypeField;
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string locale {
            get {
                return this.localeField;
            }
            set {
                this.localeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mime-type", IsNullable=true)]
        public string mimetype {
            get {
                return this.mimetypeField;
            }
            set {
                this.mimetypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfobject.sfapi.successfactors.com")]
    public partial class EntityInfo {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfobject.sfapi.successfactors.com")]
    public partial class DescribeExResult {
        
        private string typeField;
        
        private EntityInfo entityInfoField;
        
        private FieldEx[] fieldField;
        
        private featureType[] featureField;
        
        private Error[] errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public EntityInfo entityInfo {
            get {
                return this.entityInfoField;
            }
            set {
                this.entityInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("field", IsNullable=true)]
        public FieldEx[] field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("feature")]
        public featureType[] feature {
            get {
                return this.featureField;
            }
            set {
                this.featureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error", IsNullable=true)]
        public Error[] error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfobject.sfapi.successfactors.com")]
    public enum featureType {
        
        /// <remarks/>
        insert,
        
        /// <remarks/>
        update,
        
        /// <remarks/>
        upsert,
        
        /// <remarks/>
        delete,
        
        /// <remarks/>
        query,
        
        /// <remarks/>
        queryMore,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfobject.sfapi.successfactors.com")]
    public partial class Error {
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfobject.sfapi.successfactors.com")]
    public partial class Field {
        
        private string nameField;
        
        private dataType dataTypeField;
        
        private Picklist picklistField;
        
        private Label[] labelField;
        
        private int maxlengthField;
        
        private bool maxlengthFieldSpecified;
        
        private bool requiredField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public dataType dataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        public Picklist picklist {
            get {
                return this.picklistField;
            }
            set {
                this.picklistField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("label")]
        public Label[] label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        public int maxlength {
            get {
                return this.maxlengthField;
            }
            set {
                this.maxlengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxlengthSpecified {
            get {
                return this.maxlengthFieldSpecified;
            }
            set {
                this.maxlengthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool required {
            get {
                return this.requiredField;
            }
            set {
                this.requiredField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfobject.sfapi.successfactors.com")]
    public partial class DescribeResult {
        
        private string typeField;
        
        private Field[] fieldField;
        
        private featureType[] featureField;
        
        private Error[] errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("field", IsNullable=true)]
        public Field[] field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("feature")]
        public featureType[] feature {
            get {
                return this.featureField;
            }
            set {
                this.featureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error", IsNullable=true)]
        public Error[] error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfobject.sfapi.successfactors.com")]
    public partial class LoginResult {
        
        private string sessionIdField;
        
        private System.Nullable<long> msUntilPwdExpirationField;
        
        private Error[] errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> msUntilPwdExpiration {
            get {
                return this.msUntilPwdExpirationField;
            }
            set {
                this.msUntilPwdExpirationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error", IsNullable=true)]
        public Error[] error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sfobject.sfapi.successfactors.com")]
    public partial class SFParameter {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sfobject.sfapi.successfactors.com")]
    public partial class submitQueryJob {
        
        private string queryStringField;
        
        private SFParameter[] paramField;
        
        /// <remarks/>
        public string queryString {
            get {
                return this.queryStringField;
            }
            set {
                this.queryStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("param")]
        public SFParameter[] param {
            get {
                return this.paramField;
            }
            set {
                this.paramField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sfobject.sfapi.successfactors.com")]
    public partial class submitQueryJobResponse {
        
        private TaskStatus resultField;
        
        /// <remarks/>
        public TaskStatus result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sfobject.sfapi.successfactors.com")]
    public partial class getJobResultEmbedded {
        
        private string taskIdField;
        
        /// <remarks/>
        public string taskId {
            get {
                return this.taskIdField;
            }
            set {
                this.taskIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoginResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoginResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void isValidSessionCompletedEventHandler(object sender, isValidSessionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isValidSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isValidSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void describeCompletedEventHandler(object sender, describeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class describeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal describeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DescribeResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DescribeResult[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void describeExCompletedEventHandler(object sender, describeExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class describeExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal describeExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DescribeExResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DescribeExResult[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void logoutCompletedEventHandler(object sender, logoutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class logoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal logoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void listCompletedEventHandler(object sender, listCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void queryCompletedEventHandler(object sender, queryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QueryResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QueryResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void queryMoreCompletedEventHandler(object sender, queryMoreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryMoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryMoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QueryResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QueryResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void insertCompletedEventHandler(object sender, insertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InsertResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InsertResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void updateCompletedEventHandler(object sender, updateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UpdateResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UpdateResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void upsertCompletedEventHandler(object sender, upsertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class upsertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal upsertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UpsertResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UpsertResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void deleteCompletedEventHandler(object sender, deleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeleteResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeleteResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void submitQueryJobCompletedEventHandler(object sender, submitQueryJobCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class submitQueryJobCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal submitQueryJobCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public submitQueryJobResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((submitQueryJobResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getJobResultEmbeddedCompletedEventHandler(object sender, getJobResultEmbeddedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getJobResultEmbeddedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getJobResultEmbeddedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getJobStatusCompletedEventHandler(object sender, getJobStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getJobStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getJobStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TaskStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TaskStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void listJobsCompletedEventHandler(object sender, listJobsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listJobsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listJobsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TaskStatus[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TaskStatus[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void cancelJobCompletedEventHandler(object sender, cancelJobCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelJobCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelJobCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TaskStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TaskStatus)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591